In [39]:
import numpy as np

In [148]:
PUZZLE_FILE = 'p096_sudoku.txt'
NUMBERS = {*list(range(1,10))}

def read_file(filename):
    puzzles = []
    with open(filename) as file:
        while True:
            if file.readline() == '': break
            puzzle = np.zeros(shape=(9,9))
            for i in range(9):
                puzzle[i] = [int(num) for num in file.readline().strip()]
            puzzles.append(puzzle)
    return puzzles

In [78]:
puzzles = read_file(PUZZLE_FILE)
puzzle = puzzles[0]

In [94]:
def DFS(puzzle):
    # Simply create a set of unvisited nodes (0 in them)
    unvisited = set()
    for i in range(9):
        for j in range(9):
            if not puzzle[i,j]:
                unvisited.add((i,j))

    if (DFS_rec(puzzle, unvisited)):
        print("solved")
        print(unvisited)

def DFS_rec(puzzle, unvisited):
    current = unvisited.pop() # get first node 
    

    

In [144]:
puzzle = read_file(PUZZLE_FILE)[0]
DFS(puzzle)
print(puzzle)

solved
{(4, 7), (3, 0), (2, 8), (8, 0), (7, 7), (0, 7), (2, 1), (1, 6), (3, 7), (0, 3), (5, 1), (8, 5), (5, 8), (7, 2), (1, 2), (6, 7), (8, 1), (7, 6), (4, 4), (5, 0), (4, 1), (1, 1), (6, 4), (5, 4), (0, 0), (7, 1), (4, 5), (6, 0), (1, 4), (0, 5), (8, 7), (4, 2), (0, 8), (0, 1), (2, 7), (8, 3), (4, 6), (6, 8), (6, 1), (3, 1), (5, 7), (3, 8), (2, 0), (7, 4), (8, 8), (4, 3), (1, 7), (3, 4), (2, 4)}
[[0. 0. 3. 0. 2. 0. 6. 0. 0.]
 [9. 0. 0. 3. 0. 5. 0. 0. 1.]
 [0. 0. 1. 8. 0. 6. 4. 0. 0.]
 [0. 0. 8. 1. 0. 2. 9. 0. 0.]
 [7. 0. 0. 0. 0. 0. 0. 0. 8.]
 [0. 0. 6. 7. 0. 8. 2. 0. 0.]
 [0. 0. 2. 6. 0. 9. 5. 0. 0.]
 [8. 0. 0. 2. 0. 3. 0. 0. 9.]
 [0. 0. 5. 0. 1. 0. 3. 0. 0.]]


In [161]:
curr = (0,0)

def get_column(i, j, puzzle):
    return set(puzzle[:,j])

def get_row(i,j, puzzle):
    return set(puzzle[i,:])

def get_square(i, j, puzzle):
    di, dj = (i // 3) * 3, (j // 3) * 3
    return set(puzzle[di:di+3,dj:dj+3].flatten())

def get_possibilities(i, j, puzzle):
    return NUMBERS - (get_row(i,j,puzzle) | get_column(i,j,puzzle) | get_square(i,j,puzzle))

print('row', get_row(*(curr), puzzle))
print('col', get_column(*(curr), puzzle))
print('sqr', get_square(*(curr), puzzle))

get_possibilities(*(curr), puzzle)

row {0.0, 2.0, 3.0, 6.0}
col {0.0, 9.0, 8.0, 7.0}
sqr {0.0, 9.0, 3.0, 1.0}


{4, 5}

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [163]:
def get_column(i, j, puzzle):
    return set(puzzle[:,j])

def get_row(i,j, puzzle):
    return set(puzzle[i,:])

def get_square(i, j, puzzle):
    di, dj = (i // 3) * 3, (j // 3) * 3
    return set(puzzle[di:di+3,dj:dj+3].flatten())

def get_possibilities(i, j, puzzle):
    return NUMBERS - (get_row(i,j,puzzle) | get_column(i,j,puzzle) | get_square(i,j,puzzle))

print(puzzle)
get_possibilities(0,0,puzzle)

[[0. 0. 3. 0. 2. 0. 6. 0. 0.]
 [9. 0. 0. 3. 0. 5. 0. 0. 1.]
 [0. 0. 1. 8. 0. 6. 4. 0. 0.]
 [0. 0. 8. 1. 0. 2. 9. 0. 0.]
 [7. 0. 0. 0. 0. 0. 0. 0. 8.]
 [0. 0. 6. 7. 0. 8. 2. 0. 0.]
 [0. 0. 2. 6. 0. 9. 5. 0. 0.]
 [8. 0. 0. 2. 0. 3. 0. 0. 9.]
 [0. 0. 5. 0. 1. 0. 3. 0. 0.]]


{4, 5}